version: 2
jobs:
  build_images:
    machine: true
    steps:
      - checkout
      - run:
          name: Update Cache
          command: sudo apt-get -y update
      - run:
          name: Install JQ
          command: sudo apt-get install jq
      - run:
          name: Login to Docker HUB
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Discover Jenkins tags
          # Restricted to 5 because of build are long and
          # won't fit in the circleCI free plan otherwise
          command: MAX_PAGES=1 ./download_tags.sh
      - run:
          name: Build docker images
          command:  ./build_images.sh --push

workflows:
  version: 2
  commit:
    jobs:
    - build_images
  nightly:
    triggers:
    - schedule:
        cron: "5 2 1 * *"
        filters:
          branches:
            only:
              - master
    jobs:
      - build_images
